apiVersion: v1
kind: ReplicationController
metadata:
  name: hello1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: hello1
    spec:
      containers:
        - name: hello1
          image: ghosttrio/k8s-helloworld
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello1-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    name: hello1